implement dng help command -> dng command help
Former-commit-id: 1e785481cc8ea850c8737358ccca5824d1f945bb [formerly f65ac8a2d2e72c6a4ca795aa843aeb5bcfa06c1e [formerly fdf115a43bb44b2ea9005c5e48dd74cc54895786] [formerly b81d41ab0289251c1291057adf7d2cbbd13b3520 [formerly 5bd4e6086553225ae357f8a1be955db5ddf6bdbc]]]
Former-commit-id: 78e9f9f843a99e0c3e29d397f95e721d14c5acb6 [formerly 85de0094659655d9152f157f478fe0dbb9086aa3] [formerly cd7c0c6979b3b22afb05383b9a5c0d5bb6f61ea1 [formerly af9224cc07dde0b997d9687222ad303a0917b825]]

Former-commit-id: 12891d15e71cb3eca5134ccdf2bc5c9499c52aa1 [formerly dd832e4b2a516a9210462e0dcb81239f22f5fe22]
Former-commit-id: 99974c05836a1549f7825fb5c489987bd6f378e1

diff --git a/denovogear-code/src/dng b/denovogear-code/src/dng
--- a/denovogear-code/src/dng
+++ b/denovogear-code/src/dng
@@ -3,11 +3,13 @@
 # version info
 version_num=0.1
 
-# set default location (installer should edit this)
+# set default libexec location
+# under certail conditions this may fail to work, so an installer should set
+# this to the proper installation directory, e.g. $prefix/libexec
 : ${DNG_LIBEXEC_DIR:="$( cd "$( dirname "$0" )" && pwd )"/../libexec}
 
-# Internal functions
-int_funcs="help version"
+# Internal commands
+int_cmds="help version citation"
 
 submatch () { case "$2" in *$1*) return 0 ;; *) return 1 ;; esac ; }
 
@@ -19,7 +21,8 @@ function check_libexec() {
 	fi
 }
 
-function call_command() {
+# calls external command
+function call_command_ex() {
 	check_libexec
 	cmd=$1
 	shift
@@ -32,6 +35,19 @@ function call_command() {
 	return $?
 }
 
+# calls commands
+function call_command() {
+	cmd=$1
+	# check if the command is internal
+	# other wise run external command
+	if submatch "$cmd" "$int_cmds"; then
+		dng_$cmd $@
+	else
+		call_command_ex $@
+	fi
+	return $?
+}
+
 function dng_version() {
 	echo "DeNovoGear Version $version_num"
 	return 0
@@ -39,8 +55,23 @@ function dng_version() {
 
 function dng_help() {
 	check_libexec
-	ext_cmd=`find $DNG_LIBEXEC_DIR -maxdepth 1 -type f -perm +111 -name "dng-*" -print | sed -e 's/.*dng-//'`
-	cmds="$int_funcs $ext_cmd"
+		
+	if [ -n "$2" ]; then
+		if [ "$2" = "help" ]; then
+			echo "USAGE: dng help"
+			echo "       dng help command"
+			echo ""
+			echo "Description: Displays help information."
+			echo "    The first form displays a list of available commands."
+			echo "    The second form displays the help information for a command."
+		else
+			call_command $2 "help"
+		fi
+		return $?
+	fi
+	
+	ext_cmds=`find $DNG_LIBEXEC_DIR -maxdepth 1 -type f -perm +111 -name "dng-*" -print | sed -e 's/.*dng-//'`
+	cmds="$int_cmds $ext_cmds"
 	sorted=`echo $cmds | tr ' ' '\n' | sort | tr '\n' ' '`
 	
 	echo "The following commands are supported by this installation of dng:"
@@ -49,7 +80,7 @@ function dng_help() {
 		echo "    $i"
 	done
 	echo "For more information use 'dng help command'"
-	
+	return 0
 }
 
 function dng_usage() {
@@ -58,22 +89,19 @@ function dng_usage() {
 	echo "       dng help command"
 }
 
+function dng_citation() {
+	echo "WARNING: Not yet implemented."
+	return 0
+}
 
-# the command to run is the first argument
-cmd=$1
-if [ -z $cmd ]; then
+# print usage if no arguments were given
+if [ "$#" -eq 0 ]; then
 # print help message
 	dng_usage
 	exit 0
 fi
 
-# check if the command is internal
-# other wise run external command
-if submatch "$cmd" "$int_funcs"; then
-	dng_$cmd $@
-else
-	call_command $@
-fi
+call_command $@
 
 exit $?
 
